name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'   # run every 10 minutes
  workflow_dispatch:          # lets you trigger manually from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -fsS https://kaplegal-website.onrender.com/ || true
